spring.application.name=auth-service


spring.datasource.username=authorization-server
spring.datasource.password=auth@123
spring.datasource.url=jdbc:postgresql://localhost:5432/auth-service
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


logging.level.root=info

server.error.whitelabel.enabled=false
spring.mvc.problemdetails.enabled=true